### PR TITLE
:bug: #25 - Fix broken CORS.

### LINKED ISSUE #25: Add CORS-ability
To be able to make CORS-requests, we should be able to pass the `withCredentials: true` to axios-requests. This is currently not possible, because `consumerjs/axios-http-client` cannot be imported to subclass it. This should probably be an option on the abstract-consumer.

Use case:

1. Run backend server (Django) on `http://localhost:8000`
2. Log in - session cookie is set
3. Run a docker-compose set up on `http://localhost`
4. Try to make an authorized request from `http://localhost` Javascript to `http://localhost:8000` and observe that the cookies are not sent.

### PR DESCRIPTION
**Pull request by svenvandescheur**
@sergei-maertens can you confirm that this fixes #25 ?

### CODE REVIEW

File: src/axios-http-client.js [hunk 1]
```diff
@@ -41,7 +41,8 @@ export class AxiosHTTPClient extends AbstractHTTPClient {
             headers: this.headers,
             params: query,
             transformResponse: json => json,  // Use Consumer instance for parsing.
-            data: JSON.stringify(data)  // Bypass Axios serializer for data.
+            data: JSON.stringify(data),  // Bypass Axios serializer for data.
+            withCredentials: true,
```
Comment (sergei-maertens) [inline src/axios-http-client.js]: I'm not sure if we want to _always_ do this, but let's enable it by default for now
